# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import object_extraction_pb2 as object__extraction__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in object_extraction_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ObjectExtractorStub:
    """The service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractObjects = channel.unary_unary(
                '/object_extraction.ObjectExtractor/ExtractObjects',
                request_serializer=object__extraction__pb2.ExtractionRequest.SerializeToString,
                response_deserializer=object__extraction__pb2.ExtractionResponse.FromString,
                _registered_method=True)


class ObjectExtractorServicer:
    """The service definition
    """

    def ExtractObjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectExtractorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractObjects,
                    request_deserializer=object__extraction__pb2.ExtractionRequest.FromString,
                    response_serializer=object__extraction__pb2.ExtractionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'object_extraction.ObjectExtractor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('object_extraction.ObjectExtractor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObjectExtractor:
    """The service definition
    """

    @staticmethod
    def ExtractObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/object_extraction.ObjectExtractor/ExtractObjects',
            object__extraction__pb2.ExtractionRequest.SerializeToString,
            object__extraction__pb2.ExtractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
