# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: object_extraction.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'object_extraction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17object_extraction.proto\x12\x11object_extraction\">\n\x11\x45xtractionRequest\x12\x13\n\x0bimage_bytes\x18\x01 \x03(\x0c\x12\x14\n\x0cimage_format\x18\x02 \x01(\t\"o\n\x0e\x44\x65tectedObject\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\r\n\x05x_min\x18\x03 \x01(\x02\x12\r\n\x05y_min\x18\x04 \x01(\x02\x12\r\n\x05x_max\x18\x05 \x01(\x02\x12\r\n\x05y_max\x18\x06 \x01(\x02\"H\n\x12\x45xtractionResponse\x12\x32\n\x07objects\x18\x01 \x03(\x0b\x32!.object_extraction.DetectedObject2p\n\x0fObjectExtractor\x12]\n\x0e\x45xtractObjects\x12$.object_extraction.ExtractionRequest\x1a%.object_extraction.ExtractionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'object_extraction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXTRACTIONREQUEST']._serialized_start=46
  _globals['_EXTRACTIONREQUEST']._serialized_end=108
  _globals['_DETECTEDOBJECT']._serialized_start=110
  _globals['_DETECTEDOBJECT']._serialized_end=221
  _globals['_EXTRACTIONRESPONSE']._serialized_start=223
  _globals['_EXTRACTIONRESPONSE']._serialized_end=295
  _globals['_OBJECTEXTRACTOR']._serialized_start=297
  _globals['_OBJECTEXTRACTOR']._serialized_end=409
# @@protoc_insertion_point(module_scope)
